package com.sentinel.secscan.report;

import com.sentinel.secscan.domain.Finding;
import com.sentinel.secscan.domain.RiskRating;
import com.sentinel.secscan.domain.Role;
import com.sentinel.secscan.domain.Scan;
import com.sentinel.secscan.domain.ScanStatus;
import com.sentinel.secscan.domain.Severity;
import com.sentinel.secscan.domain.User;
import com.sentinel.secscan.domain.Website;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Reopens the generated bytes with PDFBox and extracts the text back out
 * (PDFTextStripper), a real round-trip check that the report actually
 * contains the right content, not just that it produced non-empty bytes.
 */
class PdfReportGeneratorTest {

    private final PdfReportGenerator generator = new PdfReportGenerator();

    @Test
    void generatesAValidPdfContainingScanDetailsAndFindings() throws Exception {
        Scan scan = completedScan();
        List<Finding> findings = List.of(
                new Finding(scan, "https-usage", Severity.INFO, "Website is served over HTTPS.", "No action needed."),
                new Finding(scan, "hsts", Severity.HIGH, "Strict-Transport-Security header is missing.", "Add a Strict-Transport-Security header.")
        );

        byte[] pdf = generator.generate(scan, findings);

        assertThat(pdf).isNotEmpty();
        assertThat(new String(pdf, 0, 5, java.nio.charset.StandardCharsets.US_ASCII)).isEqualTo("%PDF-");

        String text;
        try (PDDocument document = Loader.loadPDF(pdf)) {
            text = new PDFTextStripper().getText(document);
            assertThat(document.getNumberOfPages()).isEqualTo(1);
        }

        assertThat(text).contains("https://example.com");
        assertThat(text).contains("HIGH");
        assertThat(text).contains("https-usage");
        assertThat(text).contains("hsts");
        assertThat(text).contains("Strict-Transport-Security header is missing.");
    }

    @Test
    void spansMultiplePagesWhenFindingsOverflowOnePage() throws Exception {
        Scan scan = completedScan();
        List<Finding> findings = new ArrayList<>();
        String longDescription = "This is a long finding description that repeats to force line wrapping. ".repeat(6);
        for (int i = 0; i < 15; i++) {
            findings.add(new Finding(scan, "check-" + i, Severity.MEDIUM, longDescription, "Fix it."));
        }

        byte[] pdf = generator.generate(scan, findings);

        try (PDDocument document = Loader.loadPDF(pdf)) {
            assertThat(document.getNumberOfPages()).isGreaterThan(1);
        }
    }

    private Scan completedScan() {
        User owner = new User("owner@example.com", "hash", Role.USER);
        Website website = new Website(owner, "https://example.com");
        Scan scan = new Scan(website);
        scan.setStatus(ScanStatus.COMPLETED);
        scan.setOverallScore(75);
        scan.setRiskRating(RiskRating.HIGH);
        scan.setCompletedAt(Instant.now());
        return scan;
    }
}
